#!/usr/bin/python3

import os
import sys
import time



DOCKER_COMMANDS = ['up', 'down', 'restart', 'build', 'start', 'stop']

def main(args):  
  if len(args) == 1 and args[0] in DOCKER_COMMANDS:
    os.system('docker-compose {}'.format(args[0]))    
  else:
    os.system('docker-compose run web python3 src/manage.py {}'.format(" ".join(args)))
  


if __name__ == '__main__':
  main(sys.argv[1:])